# Generated by Django 4.2 on 2024-12-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='abr',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='nombre',
        ),
        migrations.AddField(
            model_name='categoria',
            name='Abr',
            field=models.CharField(default='DEF', max_length=4),
        ),
        migrations.AddField(
            model_name='categoria',
            name='Cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categoria',
            name='Nombre',
            field=models.CharField(default='Sin nombre', max_length=50),
        ),
    ]
