# Generated by Django 4.2 on 2025-05-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='usuario',
            field=models.CharField(default='', max_length=200),
        ),
    ]
