# Generated by Django 4.2 on 2025-02-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_categoria_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='usuario',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
